Laba1Web/Laba1Web/urls.py
from django.contrib import admin
from django.urls import include, path

from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView

from blog.serializers import MyApiRouter

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('api/', include((MyApiRouter.urls, ''))),
    path('api/schema/', SpectacularAPIView.as_view(), name='api_schema'),
    path('api/redoc/', SpectacularRedocView.as_view(url_name='api_schema'), name='api_redoc'),
]

Laba1Web/blog/urls.py
from django.urls import path, include
from . import views
from .models import ConnectedUser

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('about/', views.about_view, name='about'),

    path('profile/<int:pk>', views.ProfileView.as_view(), name='profile'),
    path('archive', views.PostsView.as_view(), name='archive'),
    path('post/<int:pk>', views.blogpost_view, name='blogpost'),
    path('post/new', views.NewPostView.as_view(), name='new_post'),
    path('comment/<int:pk>/delete', views.delete_comment, name='delete_comment'),
    path('post/<int:pk>/delete', views.delete_post, name='delete_post'),
    path('post/<int:pk>/vote', views.post_vote, name='vote'),

    path('chat', views.chat_view, name='chat'),
    path('chat/connected', views.connected_view, name='connected'),
]

ConnectedUser.objects.all().delete()

Laba1Web/blog/models.py
from django.db import models
from django.conf import settings


class BlogUser(models.Model):
    gender_choices = [
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('None', 'Unspecified')
    ]

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_user')
    birth_date = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=10, choices=gender_choices, default='None')

    def __str__(self):
        return self.user.username


class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=1000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    posted = models.DateTimeField(auto_now_add=True)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    def __str__(self):
        return self.title + ' ' + self.author.username


class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='comments')
    text = models.CharField(max_length=500, blank=False)
    posted = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk) + ' ' + self.post.title + ' ' + self.user.username


class Vote(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='votes')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    upvote = models.BooleanField(null=True)

    def __str__(self):
        return self.post.title + ' ' + self.user.username + ' ' + str(self.upvote)


class ConnectedUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                related_name='connected_user', default=0, editable=False, unique=True)
    connected = models.TimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

Laba1Web/blog/forms.py
from django import forms
from django.core.exceptions import NON_FIELD_ERRORS
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm, PasswordResetForm, UsernameField)
from django.contrib.auth import models as auth_models, get_user_model
from django.forms.utils import ErrorList

from . import models as M


class UserRegisterForm(forms.Form):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'placeholder': 'Enter username'}))
    email = forms.EmailField(widget=forms.EmailInput())
    password = forms.CharField(
        label=("Password"),
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}),
        strip=False,
    )
    password_confirm = forms.CharField(
        label=("Repeat password"),
        widget=forms.PasswordInput(attrs={'placeholder': 'Repeat password'}),
        strip=False,
    )
    first_name = forms.CharField(max_length=128, widget=forms.TextInput())
    last_name = forms.CharField(max_length=128, widget=forms.TextInput())
    gender = forms.ChoiceField(choices=M.BlogUser.gender_choices, widget=forms.Select())
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}))

    def clean_password_confirm(self):
        pass1 = self.cleaned_data.get('password')
        pass2 = self.cleaned_data.get('password_confirm')
        if not pass2 or not pass2:
            raise forms.ValidationError('Password is empty')
        if pass2 != pass2:
            raise forms.ValidationError('Passwords do not match')
        return pass2

    def clean_username(self):
        try:
            same_username = get_user_model().objects.get_by_natural_key(self.cleaned_data.get('username'))
            if same_username:
                raise forms.ValidationError('Username already in use')
        except get_user_model().DoesNotExist:
            pass
        return self.cleaned_data.get('username')


class CommentForm(forms.ModelForm):
    class Meta:
        model = M.Comment
        fields = ['text']
        widgets = {'text': forms.Textarea(attrs={'class': 'textarea w-100', 'cols': False, 'rows': False})}


class PostForm(forms.ModelForm):
    class Meta:
        model = M.BlogPost
        fields = ['title', 'content']
        widgets = {'content': forms.Textarea(attrs={'class': 'textarea w-100', 'style': 'min-height:200px', 'cols': False, 'rows': False}),
                   'title': forms.TextInput(attrs={'class': 'w-100 '})}

Laba1Web/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.db.utils import IntegrityError
from django.utils.decorators import method_decorator
from django.views.generic import View, ListView, DetailView, FormView
from django.views.generic.edit import CreateView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, logout, get_user_model, views as auth_views, models as auth_models
from django.contrib.auth.forms import AuthenticationForm

from . import models as M
from . import forms as F


def index(request):
    context = dict()
    try:
        context['last_posts'] = M.BlogPost.objects.order_by('-posted')[:5]
    except M.BlogPost.objects.DoesNotExist:
        pass
    return render(request, "blog/index_page.html", context)


class LoginView(auth_views.LoginView):
    template_name = "blog/login_page.html"
    form_class = AuthenticationForm


def logout_view(request):
    logout(request)
    return redirect("blog:index")


class RegisterView(FormView):
    template_name = "blog/register_page.html"
    form_class = F.UserRegisterForm
    success_url = reverse_lazy("blog:index")

    def form_valid(self, form):
        new_user = auth_models.User.objects.create_user(form.cleaned_data['username'], form.cleaned_data['email'],
                                                        form.cleaned_data['password'])
        new_user.first_name = form.cleaned_data['first_name']
        new_user.last_name = form.cleaned_data['last_name']
        new_user.save()

        blog_user = M.BlogUser()
        blog_user.user = new_user
        blog_user.gender = form.cleaned_data['gender']
        blog_user.birth_date = form.cleaned_data['birth_date']
        try:
            blog_user.save()
        except IntegrityError:
            return super().form_invalid(form)
        login(self.request, user=new_user)
        return super().form_valid(form)


class ProfileView(DetailView):
    model = get_user_model()
    template_name = "blog/profile_page.html"
    context_object_name = 'chosen_user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog_user'] = super().get_object().blog_user
        return context


def blogpost_view(request, pk):
    selected_post = get_object_or_404(M.BlogPost, pk=pk)
    comments = M.Comment.objects.filter(post=selected_post)
    context = {'post': selected_post, 'comments': comments}
    if request.user.is_authenticated:
        comment_form = F.CommentForm()
        if request.method == 'POST':
            comment_form = F.CommentForm(request.POST)
            if comment_form.is_valid():
                saved_comment = comment_form.save(commit=False)
                saved_comment.user = request.user
                saved_comment.post = selected_post
                saved_comment.save()
                return redirect("blog:blogpost", pk)
        context['comment_form'] = comment_form
        try:
            context['vote'] = M.Vote.objects.all().get(user=request.user, post=selected_post)
        except M.Vote.DoesNotExist:
            pass
    return render(request, "blog/blogpost_page.html", context)


@login_required
def delete_comment(request, pk):
    comment = get_object_or_404(M.Comment, pk=pk)
    ret_id = comment.post.id
    if request.user == comment.user or request.user.is_staff:
        comment.delete()
        return redirect("blog:blogpost", ret_id)

    return HttpResponseForbidden("GET AWAY")


@login_required
def delete_post(request, pk):
    if request.user.is_staff:
        post = get_object_or_404(M.BlogPost, pk=pk)
        post.delete()
        return redirect("blog:index")
    return HttpResponseForbidden("GET AWAY")


@login_required
def post_vote(request, pk):
    post = get_object_or_404(M.BlogPost, pk=pk)
    up = request.GET.get('up', False)
    if up == "True":
        up = True
    # slow...
    selected_vote, exists = M.Vote.objects.get_or_create(post=post, user=request.user)
    if up:
        if selected_vote.upvote is True:
            return redirect("blog:blogpost", post.id)   # same vote, exit
        elif selected_vote.upvote is False:
            post.downvotes -= 1
        post.upvotes += 1
        selected_vote.upvote = True
    else:
        if selected_vote.upvote is False:
            return redirect("blog:blogpost", post.id)   # same vote, exit
        elif selected_vote.upvote is True:
            post.upvotes -= 1
        post.downvotes += 1
        selected_vote.upvote = False
    selected_vote.save()
    post.save()
    return redirect("blog:blogpost", post.id)


class PostsView(ListView):
    queryset = M.BlogPost.objects.all()
    allow_empty = True
    ordering = '-posted'
    paginate_by = 10
    context_object_name = 'all_posts'
    template_name = "blog/archive_page.html"


class NewPostView(LoginRequiredMixin, CreateView):
    model = M.BlogPost
    template_name = "blog/new_post_page.html"
    form_class = F.PostForm
    success_url = reverse_lazy("blog:index")

    def form_valid(self, form):
        self.object = form.save(commit=False)
        try:
            self.object.author = self.request.user
        except ValueError:
            return HttpResponseForbidden("Get out anon")
        self.object.save()
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if not (request.user.is_authenticated and request.user.is_staff):  # only staff can post
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


def about_view(request):
    return render(request, "blog/about_page.html")

@login_required
def chat_view(request):
    context = dict()
    context['my_user'] = request.user
    return render(request, 'blog/chat_page.html', context)

@login_required
def connected_view(request):
    if request.user.is_staff:
        connected_users = M.ConnectedUser.objects.all()
        return render(request, 'blog/connected_users_page.html', {'connected_users': connected_users})
    return redirect("blog:index")

Laba1Web/blog/templates/blog/about_page.html
{% extends "./base.html" %}

{% block header %} About blog {% endblock %}
{% block main %}
<h5 class="text-center p-2" > This is Django blog website created by Hodorovsij Andrij (andrij366@gmail.com).</h5>
<p class="text-center" ><a href="{% url 'api-root' %}"> API </a></p>
{% if not user.is_authenticated %}
<p class="text-center">You can  <a href="{% url 'blog:login' %}">log in</a> or <a href="{% url 'blog:register' %}" >register</a> to use it </p>
{% endif %}
{% endblock %}

Laba1Web/blog/templates/blog/archive_page.html
{% extends "./base.html" %}

{% block header %} All posts {% endblock %}

{% block main %}
<h3 class="text-center" style="padding:10px"> Browse all posts </h3>
<div class="container" >
    {% for post in all_posts %}
        <div class="media m-1 border">
            <div class="media-body pl-3">
                <h4><a href="{% url 'blog:blogpost' post.id %}" >{{ post.title }}</a></h4>
                <div class="d-flex justify-content-between px-2">By {{ post.author.username }} <small><i>Posted {{ post.posted }}</i></small></div>
            </div>
        </div>
    {% empty %}
        <p>No posts</p>
    {% endfor %}
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><-</a></li>
        {% endif %}
        <li class="page-link">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
        </li>
        {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}"> -></a></li>
        <li class="page-item"> <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}"> Last &raquo;</a> </li>
        {% endif %}
    </ul>
</div>
{% endblock %}

Laba1Web/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <title>{% block header %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block scr %} {% endblock %}
</head>
<body class="container">
<div class=" row bg-light">
    <div class="col-md-3 bg-dark">
        <ul class="nav flex-column ">
            <li class="nav-item " style="border-bottom:1px solid grey">
            <a class="nav-link display-4 " href="{% url 'blog:index' %}" style="font-size:2rem">SickBlog</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:profile' request.user.id %}">My Profile</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:chat' %}">Live chat</a>
            </li>
            {% if user.is_staff %}
                <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:new_post'%}">Create a post</a>
                </li>
            {% endif %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:login' %}">Login</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:register' %}">Register</a>
            </li>
            {% endif %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:about' %}">About</a>
            </li>
        </ul>
    </div>
    <div class="col-md-9 container bg-light py-2">
        {% block main %} No content {% endblock %}
    </div>
    <footer ></footer>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

Laba1Web/blog/templates/blog/blogpost_page.html
{% extends "./base.html" %}

{% block header %} Blog: {{ post.title }} {% endblock %}

{% block main %}

<div class="justify-content-center">
    <div class="container">
        <div class="d-flex justify-content-between py-2">
            <h5 class="text-center"> {{ post.title }} </h5>
             <div class="btn-group">
                {% if vote %}
                    {% if vote.upvote %}
                    <a class="btn border-success font-weight-bold" >{{ post.upvotes }}</a>
                    <a class="btn btn-danger" href="{% url 'blog:vote' post.id %}">{{ post.downvotes }}</a>
                    {% else %}
                    <a class="btn btn-success" href="{% url 'blog:vote' post.id %}?up=True">{{ post.upvotes }}</a>
                    <a class="btn border-danger font-weight-bolder"> {{ post.downvotes }}</a>
                    {% endif %}
                {% else %}
                    <a class="btn btn-success" href="{% url 'blog:vote' post.id %}?up=True">{{ post.upvotes }}</a>
                    <a class="btn btn-danger" href="{% url 'blog:vote' post.id %}">{{ post.downvotes }}</a>
                {% endif %}
             </div>
        </div>
        <p> {{ post.content }} </p>
        {% if post.author %}
        <i class="float-right"><a href="{% url 'blog:profile' post.author.id %}"> by {{ post.author.username }}</a></i>
        {% endif %}
    </div>
    <div class="container pt-2">
        {% if user.is_staff %}
        <a class="btn btn-danger" href="{% url 'blog:delete_post' post.id %}">Delete post</a>
        {% endif %}
        <h6> Leave a comment </h6>
        <form method="post" action="{% url 'blog:blogpost' post.id %}" >
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">
            {{ comment_form.text }}
            <input type="submit" class="btn btn-primary" value="Comment">
        </form>
    </div>
    <div class="container pt-4" id="comments">
        <h6> Comments: </h6>
        {% for comment in comments %}
            <div class="container border p-2">
                <h6>
                    <a href="{% url 'blog:profile' comment.user.id %}">{{ comment.user }}</a>
                    <small><i> {{ comment.posted }}</i></small>
                    {% if user.is_staff or user.is_authenticated and user == comment.user  %}
                        <a href="{% url 'blog:delete_comment' comment.id %}" class="float-right font-italic"> Delete</a>
                    {% endif %}
                </h6>
                <a>{{ comment.text }}</a>
            </div>
        {% empty %}
        <div class="media border"><p> No comments here yet</p></div>
        {% endfor %}
    </div>

</div>
{% endblock %}

Laba1Web/blog/templates/blog/chat_page.html
{% extends "./base.html" %}
{% block header %} Chat {% endblock %}

{% block main %}
<div class="row justify-content-center" >
    {% if user.is_staff %}
    <h5 class="text-center"> <a href="{% url 'blog:connected'%}"> Users currently online in chat</a></h5>
    {% endif %}
    <div class="container m-2 border" id="messages" style="min-height: 85vh; max-height: 500px; overflow: auto"
    </div>
</div>
<div class="form-row">
    <div class="col-md-11"><input id="chat-message-input" type="text" class="form-control mb-sm-2" size="100" ></div>
    <div class="col-md-1"><input id="chat-message-submit" type="button" class="btn btn-primary" value="Send"></div>
</div>
{{ my_user.username |json_script:"user-field" }}
<script>
    my_user = JSON.parse(document.getElementById('user-field').textContent)

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/chat/'
    );

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        const messages = document.querySelector('#messages')
        var new_row = document.createElement("DIV");
        new_row.classList.add("row")
        new_row.style.borderBottom = '1px solid lightgrey';
        if (data.author == my_user)
            new_row.style.backgroundColor = '#FFEFD5';
        else if (data.message.includes("@" + my_user))
            new_row.style.backgroundColor = '#AFEEEE';
        else if (data.class == "system")
            new_row.style.backgroundColor = '#E6E6FA';
        else if (data.class == "admin")
            new_row.style.backgroundColor = '#D9EEE1';

        new_row.innerHTML = "<div class=\"col-2\"><b> " + data.author + " </b></div><div class=\"col-10\"> " + data.message + "</div>";
        messages.appendChild(new_row);
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        const messageInputDom = document.querySelector('#chat-message-input');
        const message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'sender': my_user
        }));
        messageInputDom.value = '';
    };
</script>
{% endblock %}

Laba1Web/blog/templates/blog/connected_users_page.html
{% extends "./base.html" %}
{% block header %} Connected to chat users {% endblock %}

{% block main %}
<h5 class="text-center">Users currently online in chat: </h5>
<div class="row justify-content-center" >
    <ul class="list-group border" >
        {% for user in connected_users %}
        <li class="list-group-item">
            <a href="{% url 'blog:profile' user.user.id %}" target="_blank"> {{user.user.username}}  -- Connected: {{ user.connected }} </a>
        </li>
        {% empty %}
            <a class="list-group-item"> Chat is empty </a>
        {% endfor %}
    </ul>
</div>
{% endblock %}

Laba1Web/blog/templates/blog/index_page.html
{% extends "./base.html" %}

{% block header %} Sick blog {% endblock %}

{% block main %}
<h3 class="text-center p-2"> Fresh posts: </h3>
<div class="container" >
    {% for post in last_posts %}
        <div class="media m-1 border">
            <div class="media-body pl-3 ">
                <h4 ><a href="{% url 'blog:blogpost' post.id %}" >{{ post.title }}</a> </h4>
                <div class="d-flex justify-content-between px-2">By {{ post.author.username }} <small><i>Posted {{ post.posted }}</i></small></div>
            </div>
        </div>
    {% empty %}
        <p>No posts</p>
    {% endfor %}
    <a href="{% url 'blog:archive' %}"> More posts > </a>
</div>
{% endblock %}

Laba1Web/blog/templates/blog/login_page.html
{% extends "./base.html" %}

{% block header %} Login page {% endblock %}

{% block main %}

<div class="row justify-content-center w-100 ">
    <form method="post" action="{% url 'blog:login' %}" class="m-sm-4">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    <table>
    {{ form.as_table}}
    </table>
    <input type="submit" class="btn btn-primary" value="Log in">
    </form>
</div>
{% endblock %}

Laba1Web/blog/templates/blog/new_post_page.html
{% extends "./base.html" %}

{% block header %} New post {% endblock %}

{% block main %}
<div class="row justify-content-center">
    <h5 class="text-center">Create a new post</h5>
    <form method="post" action="{% url 'blog:new_post' %}" class="w-100 mx-1 mx-sm-4">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Post">
    </form>
</div>
{% endblock %}

Laba1Web/blog/templates/blog/profile_page.html
{% extends "./base.html" %}

{% block header %} Profile {% endblock %}

{% block main %}
    {% if chosen_user and blog_user %}
    <table class=" table ">
        <tr>
            <td>Username:</td>
            <td>{{chosen_user.username}}</td>
        </tr>
        <tr>
            <td>E-mail:</td>
            <td>{{chosen_user.email}}</td>
        </tr>
        <tr>
            <td>First name:</td>
            <td>{{chosen_user.first_name}}</td>
        </tr>
        <tr>
            <td>Last Name:</td>
            <td>{{chosen_user.last_name}}</td>
        </tr>
        <tr>
            <td>Gender:</td>
            <td>{{blog_user.gender}}</td>
        </tr>
        <tr>
            <td>Birthday:</td>
            <td>{{blog_user.birth_date}}</td>
        </tr>
    </table>

    {% if user.is_authenticated and user.id == chosen_user.id %}
    <div class="container", style="padding: 20px">
        <a class="btn btn-secondary" href="{% url 'blog:logout' %}">Logout</a>
    </div>
    {% endif %}
{% endif %}
{% endblock %}

Laba1Web/blog/templates/blog/register_page.html
{% extends "./base.html" %}

{% block header %} Login page {% endblock %}

{% block main %}

<div class="row justify-content-center">
    <form method="post" action="{% url 'blog:register' %}" style="width:500px; max-width: 500px; margin:10px">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
        <table class=" table ">
        {{ form.as_table }}
        </table>
    <input type="submit" class="btn btn-primary" value="Register">
    </form>
</div>
{% endblock %}